[build]
builder = "nixpacks"
buildCommand = "echo building!"

[deploy]
preDeployCommand = ["npm run migrate"]
startCommand = "echo starting!"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
